Repository AY2223S1-CS2103-F14-3/tp, pull requests merged in 2022-10, with the labels that each got.

#53 Create fields for application model
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/application/Company.java
  src/main/java/seedu/address/model/application/CompanyContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/application/Contact.java
  src/main/java/seedu/address/model/application/Date.java
  src/main/java/seedu/address/model/application/Email.java
  src/main/java/seedu/address/model/application/Position.java
  src/main/java/seedu/address/model/application/PositionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/application/UniqueApplicationList.java
  src/main/java/seedu/address/model/application/exceptions/ApplicationNotFoundException.java
  src/main/java/seedu/address/model/application/exceptions/DuplicateApplicationException.java
  src/main/java/seedu/address/model/application/interview/Interview.java
  src/main/java/seedu/address/model/application/interview/InterviewDate.java
  src/main/java/seedu/address/model/application/interview/InterviewTime.java
  src/main/java/seedu/address/model/application/interview/Remark.java
  src/main/java/seedu/address/model/application/interview/Round.java
  src/test/java/seedu/address/model/application/DateTest.java
Labels: type.Task, priority.High

#55 Create application model
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ApplicationBook.java
  src/main/java/seedu/address/model/ApplicationModel.java
  src/main/java/seedu/address/model/ApplicationModelManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyApplicationBook.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, priority.High

#54 Update and refactor command parameters to fit CinternS
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ApplicationAddCommand.java
  src/main/java/seedu/address/logic/commands/ApplicationCommand.java
  src/main/java/seedu/address/logic/commands/ApplicationDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ApplicationExitCommand.java
  src/main/java/seedu/address/logic/commands/ApplicationListCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Task, priority.High

#57 Change dateString input format validation
  src/main/java/seedu/address/model/application/Date.java
  src/main/java/seedu/address/model/application/interview/InterviewDate.java
  src/test/java/seedu/address/model/application/DateTest.java
Labels: type.Bug, severity.Medium

#56 Update Parser to accept new parameters
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ApplicationAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/address/logic/parser/ApplicationDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ApplicationParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/ApplicationCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ApplicationAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ApplicationCommandParserTestUtil.java
  src/test/java/seedu/address/testutil/ApplicationBuilder.java
  src/test/java/seedu/address/testutil/ApplicationTestUtil.java
  src/test/java/seedu/address/testutil/TypicalApplications.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#58 Update UI to display sample applications
  src/main/java/seedu/address/ApplicationMain.java
  src/main/java/seedu/address/ApplicationMainApp.java
  src/main/java/seedu/address/logic/ApplicationLogic.java
  src/main/java/seedu/address/logic/ApplicationLogicManager.java
  src/main/java/seedu/address/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/address/model/util/SampleDataUtilApplicationBook.java
  src/main/java/seedu/address/storage/ApplicationBookStorage.java
  src/main/java/seedu/address/storage/ApplicationStorage.java
  src/main/java/seedu/address/storage/ApplicationStorageManager.java
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/main/java/seedu/address/storage/JsonApplicationBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableApplicationBook.java
  src/main/java/seedu/address/ui/ApplicationCard.java
  src/main/java/seedu/address/ui/ApplicationHelpWindow.java
  src/main/java/seedu/address/ui/ApplicationListPanel.java
  src/main/java/seedu/address/ui/ApplicationMainWindow.java
  src/main/java/seedu/address/ui/ApplicationUiManager.java
  src/main/java/seedu/address/ui/ApplicationUiPart.java
  src/main/resources/images/internship.png
  src/main/resources/view/ApplicationHelpWindow.fxml
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/ApplicationListPanel.fxml
  src/main/resources/view/ApplicationMainWindow.fxml
Labels: type.Task, priority.High

#68 Fix ListCommand bug
  src/main/java/seedu/address/logic/commands/ApplicationListCommand.java
Labels: type.Bug, severity.Low

#59 Branch update storage test
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/test/data/JsonApplicationBookStorageTest/invalidAndValidApplicationApplicationBook.json
  src/test/data/JsonApplicationBookStorageTest/invalidApplicationApplicationBook.json
  src/test/data/JsonApplicationBookStorageTest/notJsonFormatApplicationBook.json
  src/test/data/JsonSerializableApplicationBookTest/duplicateApplicationApplicationBook.json
  src/test/data/JsonSerializableApplicationBookTest/invalidApplicationApplicationBook.json
  src/test/data/JsonSerializableApplicationBookTest/typicalApplicationApplicationBook.json
  src/test/java/seedu/address/storage/ApplicationStorageManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/address/storage/JsonApplicationBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableApplicationBookTest.java
Labels: type.Task, priority.Medium

#73 Create model tests
  src/test/java/seedu/address/model/ApplicationBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/application/CompanyContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/application/CompanyTest.java
  src/test/java/seedu/address/model/application/ContactTest.java
  src/test/java/seedu/address/model/application/EmailTest.java
  src/test/java/seedu/address/model/application/PositionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/application/PositionTest.java
  src/test/java/seedu/address/model/application/UniqueApplicationListTest.java
  src/test/java/seedu/address/testutil/ApplicationBookBuilder.java
Labels: type.Task, priority.High

#72 Update Clear and Help commands
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Task, priority.High

#76 Add missing spaces to AddCommand usage message
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, severity.VeryLow

#77 Update tests for various commands
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicationDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: type.Task, priority.High

#78 Delete Interview fields
  src/main/java/seedu/address/model/application/interview/Interview.java
  src/main/java/seedu/address/model/application/interview/InterviewDate.java
  src/main/java/seedu/address/model/application/interview/InterviewTime.java
  src/main/java/seedu/address/model/application/interview/Remark.java
  src/main/java/seedu/address/model/application/interview/Round.java
Labels: priority.Medium

#79 Fix Date display bug in UI
  src/main/java/seedu/address/ui/ApplicationCard.java
Labels: type.Bug, severity.Low

#81 Migrate remaining tests
  src/main/java/seedu/address/model/application/Date.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/ApplicationBookParserTest.java
  src/test/java/seedu/address/model/application/ApplicationTest.java
  src/test/java/seedu/address/testutil/ApplicationUtil.java
Labels: type.Task, priority.High

#83 Fix minor bug from deleting deprecated code
  src/main/java/seedu/application/logic/parser/AddCommandParser.java
  src/main/java/seedu/application/logic/parser/Prefix.java
Labels: type.Bug, severity.Low

#94 Rename remaining "address" instances
  build.gradle
  src/main/java/seedu/application/logic/commands/ClearCommand.java
  src/main/java/seedu/application/model/application/Company.java
Labels: type.Bug

#90 Add tag as application field
  docs/UserGuide.md
  src/main/java/seedu/application/logic/commands/AddCommand.java
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/parser/AddCommandParser.java
  src/main/java/seedu/application/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/application/logic/parser/CliSyntax.java
  src/main/java/seedu/application/logic/parser/EditCommandParser.java
  src/main/java/seedu/application/logic/parser/ParserUtil.java
  src/main/java/seedu/application/model/application/Application.java
  src/main/java/seedu/application/model/tag/Tag.java
  src/main/java/seedu/application/model/util/SampleDataUtil.java
  src/main/java/seedu/application/storage/JsonAdaptedApplication.java
  src/main/java/seedu/application/storage/JsonAdaptedTag.java
  src/main/java/seedu/application/ui/ApplicationCard.java
  src/main/resources/view/ApplicationListCard.fxml
  src/test/data/JsonSerializableApplicationBookTest/typicalApplicationApplicationBook.json
  src/test/java/seedu/application/logic/LogicManagerTest.java
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/logic/commands/EditApplicationDescriptorTest.java
  src/test/java/seedu/application/logic/commands/EditCommandTest.java
  src/test/java/seedu/application/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/application/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/application/logic/parser/ParserUtilTest.java
  src/test/java/seedu/application/model/ApplicationBookTest.java
  src/test/java/seedu/application/model/application/ApplicationTest.java
  src/test/java/seedu/application/model/application/UniqueApplicationListTest.java
  src/test/java/seedu/application/model/tag/TagTest.java
  src/test/java/seedu/application/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/application/testutil/ApplicationBuilder.java
  src/test/java/seedu/application/testutil/ApplicationUtil.java
  src/test/java/seedu/application/testutil/EditApplicationDescriptorBuilder.java
  src/test/java/seedu/application/testutil/TypicalApplications.java
Labels: type.Task, priority.Medium

#96 jh update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddInterviewSequenceDiagram.puml
  docs/diagrams/ApplicationClassDiagram.puml
  docs/images/AddInterviewSequenceDiagram.png
  docs/images/ApplicationClassDiagram.png
Labels: type.Documentation

#92 Add interview as application field
  src/main/java/seedu/application/MainApp.java
  src/main/java/seedu/application/commons/core/Messages.java
  src/main/java/seedu/application/logic/Logic.java
  src/main/java/seedu/application/logic/LogicManager.java
  src/main/java/seedu/application/logic/commands/AddCommand.java
  src/main/java/seedu/application/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/application/logic/commands/DeleteCommand.java
  src/main/java/seedu/application/logic/commands/DeleteInterviewCommand.java
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/parser/AddInterviewCommandParser.java
  src/main/java/seedu/application/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/application/logic/parser/CliSyntax.java
  src/main/java/seedu/application/logic/parser/DeleteInterviewCommandParser.java
  src/main/java/seedu/application/logic/parser/ParserUtil.java
  src/main/java/seedu/application/model/ApplicationBook.java
  src/main/java/seedu/application/model/Model.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/model/application/Application.java
  src/main/java/seedu/application/model/application/UniqueApplicationList.java
  src/main/java/seedu/application/model/application/interview/Interview.java
  src/main/java/seedu/application/model/application/interview/InterviewComparator.java
  src/main/java/seedu/application/model/application/interview/InterviewDate.java
  src/main/java/seedu/application/model/application/interview/InterviewTime.java
  src/main/java/seedu/application/model/application/interview/Location.java
  src/main/java/seedu/application/model/application/interview/Round.java
  src/main/java/seedu/application/model/application/interview/exceptions/DuplicateInterviewException.java
  src/main/java/seedu/application/model/application/interview/exceptions/InvalidInterviewException.java
  src/main/java/seedu/application/model/util/SampleDataUtil.java
  src/main/java/seedu/application/storage/JsonAdaptedApplication.java
  src/main/java/seedu/application/storage/JsonSerializableApplicationBook.java
  src/main/java/seedu/application/ui/InterviewCard.java
  src/main/java/seedu/application/ui/InterviewListPanel.java
  src/main/java/seedu/application/ui/MainWindow.java
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InterviewCard.fxml
  src/main/resources/view/InterviewListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonApplicationBookStorageTest/invalidAndValidApplicationApplicationBook.json
  src/test/data/JsonSerializableApplicationBookTest/duplicateApplicationApplicationBook.json
  src/test/data/JsonSerializableApplicationBookTest/typicalApplicationApplicationBook.json
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/model/application/interview/InterviewDateTest.java
  src/test/java/seedu/application/model/application/interview/InterviewTimeTest.java
  src/test/java/seedu/application/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/application/testutil/ApplicationBuilder.java
  src/test/java/seedu/application/testutil/InterviewBuilder.java
  src/test/java/seedu/application/testutil/TypicalApplications.java
  src/test/java/seedu/application/testutil/TypicalInterviews.java
Labels: type.Task, priority.High

#100 Update DG with design considerations for Find feature
  docs/DeveloperGuide.md
Labels: type.Documentation

#104 Allow bypass of the Interview itself when checking for duplicates
  src/main/java/seedu/application/model/application/UniqueApplicationList.java
Labels: type.Bug, severity.Medium

#98 Add Undo and Redo commands
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/commands/RedoCommand.java
  src/main/java/seedu/application/logic/commands/UndoCommand.java
  src/main/java/seedu/application/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/application/model/Model.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/model/VersionedApplicationBook.java
  src/main/java/seedu/application/model/application/UniqueApplicationList.java
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/ClearCommandTest.java
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/logic/commands/EditCommandTest.java
  src/test/java/seedu/application/logic/commands/RedoCommandTest.java
  src/test/java/seedu/application/logic/commands/UndoCommandTest.java
  src/test/java/seedu/application/logic/parser/ApplicationBookParserTest.java
  src/test/java/seedu/application/model/ModelManagerTest.java
  src/test/java/seedu/application/model/VersionedApplicationBookTest.java
  src/test/java/seedu/application/testutil/TypicalCommands.java
Labels: type.Story, priority.High

#99 Implement sort feature
  src/main/java/seedu/application/logic/commands/SortByCompanyCommand.java
  src/main/java/seedu/application/logic/commands/SortByDateCommand.java
  src/main/java/seedu/application/logic/commands/SortByPositionCommand.java
  src/main/java/seedu/application/logic/commands/SortCommand.java
  src/main/java/seedu/application/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/application/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/application/logic/parser/CliSyntax.java
  src/main/java/seedu/application/logic/parser/SortCommandParser.java
  src/main/java/seedu/application/model/Model.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/model/application/Company.java
  src/main/java/seedu/application/model/application/Date.java
  src/main/java/seedu/application/model/application/Position.java
  src/main/java/seedu/application/storage/JsonAdaptedApplication.java
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/SortByCompanyCommandTest.java
  src/test/java/seedu/application/logic/commands/SortByDateCommandTest.java
  src/test/java/seedu/application/logic/commands/SortByPositionCommandTest.java
  src/test/java/seedu/application/logic/parser/ApplicationBookParserTest.java
  src/test/java/seedu/application/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/application/model/ModelManagerTest.java
  src/test/java/seedu/application/model/application/CompanyTest.java
  src/test/java/seedu/application/model/application/DateTest.java
  src/test/java/seedu/application/model/application/PositionTest.java
Labels: type.Story, priority.Medium

#102 Modify UI to include label for date applied
  docs/UserGuide.md
  src/main/java/seedu/application/logic/commands/AddCommand.java
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.Medium

#109 Add sorting feature to developer guide
  docs/DeveloperGuide.md
  docs/diagrams/SortClassDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortClassDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: type.Documentation

#110 Enable assertions
  build.gradle
Labels: type.Task, priority.High

#117 Implement sort by interview feature
  src/main/java/seedu/application/logic/commands/SortByCompanyCommand.java
  src/main/java/seedu/application/logic/commands/SortByDateCommand.java
  src/main/java/seedu/application/logic/commands/SortByInterviewCommand.java
  src/main/java/seedu/application/logic/commands/SortByPositionCommand.java
  src/main/java/seedu/application/logic/parser/SortCommandParser.java
  src/main/java/seedu/application/model/Model.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/model/application/Application.java
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/SortByInterviewCommandTest.java
  src/test/java/seedu/application/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/application/model/ModelManagerTest.java
Labels: type.Story, priority.Medium

#112 Add remind command feature
  src/main/java/seedu/application/logic/Logic.java
  src/main/java/seedu/application/logic/LogicManager.java
  src/main/java/seedu/application/logic/commands/AddCommand.java
  src/main/java/seedu/application/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/application/logic/commands/CommandResult.java
  src/main/java/seedu/application/logic/commands/ExitCommand.java
  src/main/java/seedu/application/logic/commands/HelpCommand.java
  src/main/java/seedu/application/logic/commands/RemindCommand.java
  src/main/java/seedu/application/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/application/model/Model.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/model/application/Application.java
  src/main/java/seedu/application/model/application/UpcomingInterviewPredicate.java
  src/main/java/seedu/application/model/application/interview/Interview.java
  src/main/java/seedu/application/model/util/SampleDataUtil.java
  src/main/java/seedu/application/ui/InterviewListPanel.java
  src/main/java/seedu/application/ui/MainWindow.java
  src/main/java/seedu/application/ui/ReminderWindow.java
  src/main/resources/images/alarm.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReminderWindow.css
  src/main/resources/view/ReminderWindow.fxml
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/CommandResultTest.java
  src/test/java/seedu/application/logic/commands/ExitCommandTest.java
  src/test/java/seedu/application/logic/commands/HelpCommandTest.java
Labels: type.Task, priority.Medium

#121 Add Status of application
  src/main/java/seedu/application/logic/commands/AddCommand.java
  src/main/java/seedu/application/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/commands/ListArchiveCommand.java
  src/main/java/seedu/application/logic/commands/ListCommand.java
  src/main/java/seedu/application/logic/commands/SortByCompanyCommand.java
  src/main/java/seedu/application/logic/commands/SortByDateCommand.java
  src/main/java/seedu/application/logic/commands/SortByInterviewCommand.java
  src/main/java/seedu/application/logic/commands/SortByPositionCommand.java
  src/main/java/seedu/application/logic/commands/SortCommand.java
  src/main/java/seedu/application/logic/parser/AddCommandParser.java
  src/main/java/seedu/application/logic/parser/CliSyntax.java
  src/main/java/seedu/application/logic/parser/EditCommandParser.java
  src/main/java/seedu/application/logic/parser/ParserUtil.java
  src/main/java/seedu/application/model/ApplicationBook.java
  src/main/java/seedu/application/model/application/Application.java
  src/main/java/seedu/application/model/application/Status.java
  src/main/java/seedu/application/model/application/UniqueApplicationList.java
  src/main/java/seedu/application/model/util/SampleDataUtil.java
  src/main/java/seedu/application/storage/JsonAdaptedApplication.java
  src/main/java/seedu/application/ui/ApplicationCard.java
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableApplicationBookTest/duplicateApplicationApplicationBook.json
  src/test/data/JsonSerializableApplicationBookTest/invalidApplicationApplicationBook.json
  src/test/data/JsonSerializableApplicationBookTest/typicalApplicationApplicationBook.json
  src/test/java/seedu/application/logic/LogicManagerTest.java
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/logic/commands/EditApplicationDescriptorTest.java
  src/test/java/seedu/application/logic/commands/RedoCommandTest.java
  src/test/java/seedu/application/logic/commands/UndoCommandTest.java
  src/test/java/seedu/application/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/application/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/application/model/application/StatusTest.java
  src/test/java/seedu/application/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/application/testutil/ApplicationBuilder.java
  src/test/java/seedu/application/testutil/ApplicationUtil.java
  src/test/java/seedu/application/testutil/EditApplicationDescriptorBuilder.java
  src/test/java/seedu/application/testutil/TypicalApplications.java
  src/test/java/seedu/application/testutil/TypicalCommands.java
Labels: type.Story, priority.High

#130 Add the sort command to the user guide
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#127 Add tests for remind feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/RemindSequenceDiagram.puml
  docs/images/RemindSequenceDiagram.png
  src/test/java/seedu/application/logic/commands/RemindCommandStub.java
  src/test/java/seedu/application/logic/commands/RemindCommandTest.java
  src/test/java/seedu/application/model/application/UpcomingInterviewPredicateStub.java
  src/test/java/seedu/application/model/application/UpcomingInterviewPredicateTest.java
  src/test/java/seedu/application/testutil/TypicalApplications.java
Labels: type.Task, priority.Medium

#133 Update AddCommand help message and UG for clarity
  docs/UserGuide.md
  src/main/java/seedu/application/logic/commands/AddCommand.java
  src/main/resources/view/ReminderWindow.css
Labels: type.Bug, priority.Medium

#132 Add several UI enhancements
  src/main/java/seedu/application/model/application/Application.java
  src/main/java/seedu/application/model/application/Status.java
  src/main/java/seedu/application/ui/ApplicationCard.java
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement, priority.Medium

#134 Add stats command
  docs/UserGuide.md
  src/main/java/seedu/application/logic/commands/StatsCommand.java
  src/main/java/seedu/application/logic/parser/ApplicationBookParser.java
  src/main/java/seedu/application/model/Model.java
  src/main/java/seedu/application/model/ModelManager.java
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/StatsCommandTest.java
  src/test/java/seedu/application/testutil/TypicalApplications.java
Labels: type.Task, priority.Medium

#129 Save sort setting
  src/main/java/seedu/application/logic/commands/SortCommand.java
  src/main/java/seedu/application/model/Model.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/application/model/SortSetting.java
  src/main/java/seedu/application/model/UserPrefs.java
  src/main/java/seedu/application/model/application/UniqueApplicationList.java
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/AddInterviewCommandTest.java
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/logic/commands/FindCommandTest.java
  src/test/java/seedu/application/model/ModelManagerTest.java
  src/test/java/seedu/application/model/UserPrefsTest.java
  src/test/java/seedu/application/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/application/testutil/TypicalApplicationsWithInterview.java
Labels: type.Story, priority.Medium

#135 Enhance UI with new theme colors
  src/main/java/seedu/application/ui/ApplicationCard.java
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/InterviewCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReminderWindow.css
Labels: type.Enhancement

#137 Proofread user guide
  build.gradle
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#185 Fix edit command when application has interview
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/test/java/seedu/application/logic/commands/EditCommandTest.java
Labels: type.Bug, severity.High
