Repository AY2223S1-CS2103-F14-3/tp, pull requests merged in 2022-11, with the labels that each got.

#186 Fix text overflowing
  docs/images/FindExample.PNG
  docs/images/HelpWindow.PNG
  docs/images/Ui.png
  src/main/java/seedu/application/model/tag/Tag.java
  src/main/java/seedu/application/ui/InterviewCard.java
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InterviewCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Medium

#194 Fix interview time issue
  src/main/java/seedu/application/model/application/interview/Interview.java
  src/main/java/seedu/application/model/application/interview/InterviewTime.java
  src/test/java/seedu/application/model/application/interview/InterviewTest.java
  src/test/java/seedu/application/model/application/interview/InterviewTimeTest.java
Labels: type.Bug, severity.Medium

#188 Fix parse integer overflow error message
  src/main/java/seedu/application/commons/util/StringUtil.java
  src/main/java/seedu/application/logic/parser/AddInterviewCommandParser.java
  src/main/java/seedu/application/logic/parser/ArchiveCommandParser.java
  src/main/java/seedu/application/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/application/logic/parser/EditCommandParser.java
  src/main/java/seedu/application/logic/parser/ParserUtil.java
  src/main/java/seedu/application/logic/parser/RemoveInterviewCommandParser.java
  src/main/java/seedu/application/logic/parser/RetrieveCommandParser.java
  src/main/java/seedu/application/logic/parser/exceptions/ParseIntegerOverflowException.java
  src/test/java/seedu/application/commons/util/StringUtilTest.java
  src/test/java/seedu/application/logic/parser/AddInterviewCommandParserTest.java
  src/test/java/seedu/application/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/application/logic/parser/ParserUtilTest.java
Labels: type.Bug, severity.Medium

#195 Change company and position to be case-insensitive
  src/main/java/seedu/application/model/application/Company.java
  src/main/java/seedu/application/model/application/Position.java
  src/test/java/seedu/application/model/application/ApplicationTest.java
Labels: type.Bug, severity.Low

#196 Fix documentation bugs and update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/RemindSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/RemindSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Bug, type.Task, severity.Medium, type.Documentation

#191 Fix remind list
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchiveSequenceDiagram.puml
  docs/diagrams/RemindSequenceDiagram.puml
  docs/images/ModelManagerUsingArchiveSequenceDiagram.png
  docs/images/RemindSequenceDiagram.png
  src/main/java/seedu/application/logic/Logic.java
  src/main/java/seedu/application/logic/LogicManager.java
  src/main/java/seedu/application/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/application/logic/commands/ArchiveCommand.java
  src/main/java/seedu/application/logic/commands/ClearCommand.java
  src/main/java/seedu/application/logic/commands/DeleteCommand.java
  src/main/java/seedu/application/logic/commands/EditCommand.java
  src/main/java/seedu/application/logic/commands/ListArchiveCommand.java
  src/main/java/seedu/application/logic/commands/ListCommand.java
  src/main/java/seedu/application/logic/commands/RedoCommand.java
  src/main/java/seedu/application/logic/commands/RemindCommand.java
  src/main/java/seedu/application/logic/commands/RemoveInterviewCommand.java
  src/main/java/seedu/application/logic/commands/RetrieveCommand.java
  src/main/java/seedu/application/logic/commands/UndoCommand.java
  src/main/java/seedu/application/model/Model.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/model/application/interview/InterviewComparator.java
  src/main/java/seedu/application/model/application/interview/InterviewDate.java
  src/main/java/seedu/application/ui/MainWindow.java
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/logic/commands/RemindCommandStub.java
  src/test/java/seedu/application/logic/commands/RemindCommandTest.java
  src/test/java/seedu/application/testutil/InterviewBuilder.java
  src/test/java/seedu/application/testutil/TypicalApplications.java
Labels: type.Bug, severity.High

#187 Fix Bug
  docs/UserGuide.md
  src/main/java/seedu/application/commons/core/Messages.java
  src/main/java/seedu/application/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/application/logic/commands/ArchiveCommand.java
  src/main/java/seedu/application/logic/commands/RetrieveCommand.java
  src/main/java/seedu/application/model/application/interview/InterviewComparator.java
  src/test/java/seedu/application/logic/commands/ArchiveCommandTest.java
  src/test/java/seedu/application/logic/commands/RetrieveCommandTest.java
Labels: type.Bug, severity.Medium

#197 Update UserGuide.md
  docs/UserGuide.md
  src/main/java/seedu/application/model/application/Contact.java
  src/test/java/seedu/application/model/application/ContactTest.java
Labels: severity.Low, type.Documentation

#200 Refactor reminder tests & update documentation (UG/PPP)
  docs/UserGuide.md
  docs/team/jolynloh.md
  src/test/java/seedu/application/logic/commands/RemindCommandStub.java
  src/test/java/seedu/application/logic/commands/RemindCommandTest.java
  src/test/java/seedu/application/model/application/UpcomingInterviewPredicateStub.java
  src/test/java/seedu/application/model/application/UpcomingInterviewPredicateTest.java
  src/test/java/seedu/application/testutil/InterviewBuilder.java
  src/test/java/seedu/application/testutil/TypicalApplications.java
Labels: priority.Medium, type.Documentation

#198 jh update documentation
  README.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindInterviewSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/FindInterviewSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/index.md
  docs/team/jhchee18.md
Labels: type.Documentation

#202 Update PPP and DG
  docs/DeveloperGuide.md
  docs/team/nmtuan2001.md
Labels: priority.High, type.Documentation

#190 Update documentation (DG/PPP)
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/StatisticSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/StatisticSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/eesung00.md
Labels: type.Documentation

#201 Add draft PPP for TK
  docs/team/teekaytai.md
Labels: priority.High, type.Documentation

#207 Fix email format message
  docs/UserGuide.md
  src/main/java/seedu/application/model/application/Email.java
Labels: type.Bug, severity.Low, type.Documentation

#205 Tk update documentation week 12
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/diagrams/SortInitialisationSequenceDiagram.puml
  docs/diagrams/SortParserSequenceDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortCommandSequenceDiagram.png
  docs/images/SortInitialisationSequenceDiagram.png
  docs/images/SortParserSequenceDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: priority.Medium, type.Documentation

#203 Improve code quality
  src/main/java/seedu/application/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/application/logic/commands/RemindCommand.java
  src/main/java/seedu/application/logic/commands/RemoveInterviewCommand.java
  src/main/java/seedu/application/model/application/Application.java
  src/main/java/seedu/application/model/application/UniqueApplicationList.java
  src/main/java/seedu/application/ui/HelpWindow.java
  src/main/java/seedu/application/ui/InterviewCard.java
  src/main/java/seedu/application/ui/ReminderWindow.java
  src/test/java/seedu/application/logic/commands/AddCommandTest.java
  src/test/java/seedu/application/model/application/ApplicationTest.java
  src/test/java/seedu/application/testutil/ApplicationBuilder.java
Labels: type.Enhancement

#208 Improve interview documentation
  docs/UserGuide.md
  docs/team/eesung00.md
  docs/team/jhchee18.md
Labels: type.Documentation

#211 Update diagram for Status feature in DG
  docs/DeveloperGuide.md
  docs/diagrams/ApplicationClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StatusClassDiagram.puml
  docs/images/ApplicationClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StatusClassDiagram.png
  docs/team/nmtuan2001.md
  src/main/java/seedu/application/model/application/Application.java
Labels: type.Documentation

#216 Touch up code
  src/main/java/seedu/application/MainApp.java
  src/main/java/seedu/application/model/ModelManager.java
  src/main/java/seedu/application/storage/JsonAdaptedApplication.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/application/logic/commands/ArchiveCommandTest.java
  src/test/java/seedu/application/logic/commands/RetrieveCommandTest.java
Labels: type.Task

#210 Finalize documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/eesung00.md
Labels: type.Documentation

#213 Tk update documentation week 13
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/SortClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/SortClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Documentation

#214 Update documentation and final checks
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/images/tracing/FindUsages.png
  docs/images/tracing/searchResultsForExecuteMethod.png
  docs/team/jolynloh.md
  docs/tutorials/TracingCode.md
Labels: priority.Medium, type.Documentation

#215 Fix unknown prefix in input
  src/main/java/seedu/application/logic/parser/AddCommandParser.java
  src/main/java/seedu/application/logic/parser/AddInterviewCommandParser.java
  src/main/java/seedu/application/logic/parser/ArchiveCommandParser.java
  src/main/java/seedu/application/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/application/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/application/logic/parser/EditCommandParser.java
  src/main/java/seedu/application/logic/parser/Parser.java
  src/main/java/seedu/application/logic/parser/RemoveInterviewCommandParser.java
  src/main/java/seedu/application/logic/parser/RetrieveCommandParser.java
  src/main/java/seedu/application/logic/parser/SortCommandParser.java
  src/main/java/seedu/application/logic/parser/exceptions/ParsePrefixException.java
  src/main/java/seedu/application/model/application/Company.java
  src/main/java/seedu/application/model/tag/Tag.java
  src/test/java/seedu/application/logic/commands/CommandTestUtil.java
  src/test/java/seedu/application/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/application/logic/parser/AddInterviewCommandParserTest.java
  src/test/java/seedu/application/logic/parser/ArchiveCommandParserTest.java
  src/test/java/seedu/application/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/application/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/application/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/application/logic/parser/RemoveInterviewCommandParserTest.java
  src/test/java/seedu/application/logic/parser/RetrieveCommandParserTest.java
  src/test/java/seedu/application/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/application/model/application/UpcomingInterviewPredicateTest.java
Labels: type.Bug, severity.Low

#217 Finalize documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jhchee18.md
Labels: type.Documentation

#218 Final changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StatusClassDiagram.puml
  docs/images/StatusClassDiagram.png
Labels: type.Documentation

#221 Finalise PPP for TK
  docs/team/teekaytai.md
Labels: type.Documentation

#219 Final check changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#222 Bold effort appendix header
  docs/DeveloperGuide.md
Labels: type.Documentation
